(ns fulcro.incubator.ui.reakit
  (:refer-clojure :exclude [list Box List])
  (:require ["reakit" :as rk]
            [fulcro.incubator.ui.core :as uc]
            [fulcro.client.primitives :as fp]
            [fulcro.client.localized-dom :as dom]))

(def arrow (uc/component-factory-localized rk/Arrow))
(def backdrop (uc/component-factory-localized rk/Backdrop))
(def base (uc/component-factory-localized rk/Base))
(def block (uc/component-factory-localized rk/Block))
(def blockquote (uc/component-factory-localized rk/Blockquote))
(def box (uc/component-factory-localized rk/Box))
(def button (uc/component-factory-localized rk/Button))
(def card (uc/component-factory-localized rk/Card))
(def code (uc/component-factory-localized rk/Code))
(def divider (uc/component-factory-localized rk/Divider))
(def field (uc/component-factory-localized rk/Field))
(def fit (uc/component-factory-localized rk/Fit))
(def flex (uc/component-factory-localized rk/Flex))
(def grid (uc/component-factory-localized rk/Grid))
(def grid-item (uc/component-factory-localized rk/Grid.Item))
(def group (uc/component-factory-localized rk/Group))
(def group-item (uc/component-factory-localized rk/Group.Item))
(def heading (uc/component-factory-localized rk/Heading))
(def hidden (uc/component-factory-localized rk/Hidden))
(def hidden-container (uc/component-factory-localized rk/Hidden.Container))
(def hidden-hide (uc/component-factory-localized rk/Hidden.Hide))
(def hidden-show (uc/component-factory-localized rk/Hidden.Show))
(def hidden-toggle (uc/component-factory-localized rk/Hidden.Toggle))
(def image (uc/component-factory-localized rk/Image))
(def inline (uc/component-factory-localized rk/Inline))
(def inline-block (uc/component-factory-localized rk/InlineBlock))
(def inline-flex (uc/component-factory-localized rk/InlineFlex))
(def input (uc/component-factory-localized rk/Input))
(def label (uc/component-factory-localized rk/Label))
(def link (uc/component-factory-localized rk/Link))
(def list (uc/component-factory-localized rk/List))
(def list-item (uc/component-factory-localized rk/List.Item))
(def navigation (uc/component-factory-localized rk/Navigation))
(def overlay (uc/component-factory-localized rk/Overlay))
(def overlay-container (uc/component-factory-localized rk/Overlay.Container))
(def overlay-hide (uc/component-factory-localized rk/Overlay.Hide))
(def overlay-show (uc/component-factory-localized rk/Overlay.Show))
(def overlay-toggle (uc/component-factory-localized rk/Overlay.Toggle))
(def paragraph (uc/component-factory-localized rk/Paragraph))
(def perpendicular (uc/component-factory-localized rk/Perpendicular))
(def popover (uc/component-factory-localized rk/Popover))
(def popover-arrow (uc/component-factory-localized rk/Popover.Arrow))
(def popover-container (uc/component-factory-localized rk/Popover.Container))
(def popover-hide (uc/component-factory-localized rk/Popover.Hide))
(def popover-show (uc/component-factory-localized rk/Popover.Show))
(def popover-toggle (uc/component-factory-localized rk/Popover.Toggle))
(def shadow (uc/component-factory-localized rk/Shadow))
(def sidebar (uc/component-factory-localized rk/Sidebar))
(def sidebar-container (uc/component-factory-localized rk/Sidebar.Container))
(def sidebar-hide (uc/component-factory-localized rk/Sidebar.Hide))
(def sidebar-show (uc/component-factory-localized rk/Sidebar.Show))
(def sidebar-toggle (uc/component-factory-localized rk/Sidebar.Toggle))
(def step (uc/component-factory-localized rk/Step))
(def step-container (uc/component-factory-localized rk/Step.Container))
(def step-hide (uc/component-factory-localized rk/Step.Hide))
(def step-next (uc/component-factory-localized rk/Step.Next))
(def step-previous (uc/component-factory-localized rk/Step.Previous))
(def step-show (uc/component-factory-localized rk/Step.Show))
(def step-toggle (uc/component-factory-localized rk/Step.Toggle))
(def table (uc/component-factory-localized rk/Table))
(def table-body (uc/component-factory-localized rk/Table.Body))
(def table-caption (uc/component-factory-localized rk/Table.Caption))
(def table-cell (uc/component-factory-localized rk/Table.Cell))
(def table-column (uc/component-factory-localized rk/Table.Column))
(def table-columngroup (uc/component-factory-localized rk/Table.ColumnGroup))
(def table-foot (uc/component-factory-localized rk/Table.Foot))
(def table-head (uc/component-factory-localized rk/Table.Head))
(def table-row (uc/component-factory-localized rk/Table.Row))
(def tabs (uc/component-factory-localized rk/Tabs))
(def tabs-container (uc/component-factory-localized rk/Tabs.Container))
(def tabs-next (uc/component-factory-localized rk/Tabs.Next))
(def tabs-panel (uc/component-factory-localized rk/Tabs.Panel))
(def tabs-previous (uc/component-factory-localized rk/Tabs.Previous))
(def tabs-tab (uc/component-factory-localized rk/Tabs.Tab))
(def tooltip (uc/component-factory-localized rk/Tooltip))
(def tooltip-arrow (uc/component-factory-localized rk/Tooltip.Arrow))

(def Arrow rk/Arrow)
(def Backdrop rk/Backdrop)
(def Base rk/Base)
(def Block rk/Block)
(def Blockquote rk/Blockquote)
(def Box rk/Box)
(def Button rk/Button)
(def Card rk/Card)
(def Code rk/Code)
(def Divider rk/Divider)
(def Field rk/Field)
(def Fit rk/Fit)
(def Flex rk/Flex)
(def Grid rk/Grid)
(def GridItem rk/Grid.Item)
(def Group rk/Group)
(def GroupItem rk/Group.Item)
(def Heading rk/Heading)
(def Hidden rk/Hidden)
(def HiddenContainer rk/Hidden.Container)
(def HiddenHide rk/Hidden.Hide)
(def HiddenShow rk/Hidden.Show)
(def HiddenToggle rk/Hidden.Toggle)
(def Image rk/Image)
(def Inline rk/Inline)
(def InlineBlock rk/InlineBlock)
(def InlineFlex rk/InlineFlex)
(def Input rk/Input)
(def Label rk/Label)
(def Link rk/Link)
(def List rk/List)
(def ListItem rk/List.Item)
(def Navigation rk/Navigation)
(def Overlay rk/Overlay)
(def OverlayContainer rk/Overlay.Container)
(def OverlayHide rk/Overlay.Hide)
(def OverlayShow rk/Overlay.Show)
(def OverlayToggle rk/Overlay.Toggle)
(def Paragraph rk/Paragraph)
(def Perpendicular rk/Perpendicular)
(def Popover rk/Popover)
(def PopoverArrow rk/Popover.Arrow)
(def PopoverContainer rk/Popover.Container)
(def PopoverHide rk/Popover.Hide)
(def PopoverShow rk/Popover.Show)
(def PopoverToggle rk/Popover.Toggle)
(def Shadow rk/Shadow)
(def Sidebar rk/Sidebar)
(def SidebarContainer rk/Sidebar.Container)
(def SidebarHide rk/Sidebar.Hide)
(def SidebarShow rk/Sidebar.Show)
(def SidebarToggle rk/Sidebar.Toggle)
(def Step rk/Step)
(def StepContainer rk/Step.Container)
(def StepHide rk/Step.Hide)
(def StepNext rk/Step.Next)
(def StepPrevious rk/Step.Previous)
(def StepShow rk/Step.Show)
(def StepToggle rk/Step.Toggle)
(def Table rk/Table)
(def TableBody rk/Table.Body)
(def TableCaption rk/Table.Caption)
(def TableCell rk/Table.Cell)
(def TableColumn rk/Table.Column)
(def TableColumnGroup rk/Table.ColumnGroup)
(def TableFoot rk/Table.Foot)
(def TableHead rk/Table.Head)
(def TableRow rk/Table.Row)
(def Tabs rk/Tabs)
(def TabsContainer rk/Tabs.Container)
(def TabsNext rk/Tabs.Next)
(def TabsPanel rk/Tabs.Panel)
(def TabsPrevious rk/Tabs.Previous)
(def TabsTab rk/Tabs.Tab)
(def Tooltip rk/Tooltip)
(def TooltipArrow rk/Tooltip.Arrow)
